### ISSUE TITLE
Latest .apk file from GitHub doesn't work.

### ISSUE THREAD

**Issue by Wasnix** [mathisdt/sdbviewer#4] opened 2019-01-26 14:59 UTC
I've downloaded and installed apk file from GitHub: 
SDBViewer_1.2_2019-01-06-08-45-47_release-signed.apk

This app cannot open any URL - neither HTTP nor HTTPS. The file in URL exists definitely. Opening URL in mobile browser on same device works.

My device is a Xiaomi Redmi 5 plus (rooted) with Android 7.1.2.

Screenshot and extracted logcat are appended.

[zephyr.log](https://github.com/mathisdt/sdbviewer/files/2799118/zephyr.log)

![screenshot_org zephyrsoft sdbviewer](https://user-images.githubusercontent.com/8307605/51788892-19469800-2183-11e9-852e-dc0d2ea2fcb0.png)

**Comment by mathisdt** [comment] 2019-01-26 16:41
You're right, this release has a problem parsing the URL. It should try to guess the scheme ("http://" or "https://") when none was given, but it tried the URL *only* with prefix. The problem is fixed in the new release 1.3.
The URL would work also in Release 1.2 when you omit the scheme (remove "https://" from the beginning), but it clearly was a bug. Sorry!

**Closed by mathisdt** 2019-01-26 16:41 UTC
